@echo off
start cmd /c "python main.py --logic Algo1 --email=algo1@email.com --name=algo1 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algo2 --email=algo2@email.com --name=algo2 --password=123456 --team etimo"
start cmd /c "python main.py --logic Novel --email=novel@email.com --name=novel --password=novel123 --team etimo"
start cmd /c "python main.py --logic Density --email=densitas@email.com --name=densitas --password=densitas123 --team etimo"
start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Novel --email=novel@email.com --name=Novel --password=123456 --team etimo"
@REM @REM start cmd /c "python main.py --logic Lidya --email=test2@email.com --name=Lidya --password=123456 --team etimo"
@REM @REM start cmd /c "python main.py --logic Diana --email=test3@email.com --name=Diana --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Algo1 --email=algo1@email.com --name=Algo1 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Algo2 --email=algo2@email.com --name=Algo2 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Algo4 --email=algo4@email.com --name=Algo4 --password=123456 --team etimo"
start cmd /c "python main.py --logic FreeDiamonds --email=freediamonds@email.com --name=FreeDiamonds --password=free --team FreeDiamonds"
