@echo off
start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
start cmd /c "python main.py --logic Random --email=test1@email.com --name=stima1 --password=123456 --team etimo"
start cmd /c "python main.py --logic Distance --email=distance@email.com --name=distance --password=distance123 --team etimo"
start cmd /c "python main.py --logic Density --email=density@email.com --name=density --password=density123 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test@email.com --name=stima --password=123456 --team etimo"
start cmd /c "python main.py --logic Novel --email=novel@email.com --name=Novel --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Lidya --email=test2@email.com --name=Lidya --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Diana --email=test3@email.com --name=Diana --password=123456 --team etimo"
start cmd /c "python main.py --logic Algo1 --email=algo1@email.com --name=Algo1 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algo2 --email=algo2@email.com --name=Algo2 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algo4 --email=algo4@email.com --name=Algo4 --password=123456 --team etimo"
